#ifndef QUEST_OBJECT_TYPES_H
#define QUEST_OBJECT_TYPES_H

typedef enum  {
    QUEST_NULL = 0,
    QUEST_CONTAINER, // ie quest_composite
    QUEST_LOCATION,
    QUEST_DOOR,
    QUEST_LOCK,
    QUEST_KEY,
    QUEST_SPELL,
    // for the test harnesses...
    QUEST_SWORD,
    QUEST_CHEST,
    QUEST_GOLD,
    QUEST_RING,
    QUEST_SCROLL,
    QUEST_POTION,
    QUEST_INVENTORY,
    QUEST_PLAYER,
    QUEST_MERCHANT,
    QUEST_DUNGEON,
    QUEST_ARMOR,
    QUEST_ROOM,
    QUEST_BOOK,
    QUEST_SHIELD,
    QUEST_TAVERN,
    QUEST_NPC,
    QUEST_CHAIR,
    QUEST_TABLE,
    QUEST_LIBRARY,
    QUEST_GEM,

    QUEST_CONNECTOR_PASSAGE,
    QUEST_CONNECTOR_STAIRS

} quest_object_t;

static const char* QUEST_OBJECT_NAMES[] = {
    [QUEST_NULL] = "NULL",
    [QUEST_CONTAINER] = "CONTAINER",
    [QUEST_LOCATION] = "LOCATION",
    [QUEST_DOOR] = "DOOR",
    [QUEST_LOCK] = "LOCK",
    [QUEST_KEY] = "KEY",
    [QUEST_SPELL] = "SPELL",
    [QUEST_SWORD] = "SWORD",
    [QUEST_CHEST] = "CHEST",
    [QUEST_GOLD] = "GOLD",
    [QUEST_RING] = "RING",
    [QUEST_SCROLL] = "SCROLL",
    [QUEST_POTION] = "POTION",
    [QUEST_INVENTORY] = "INVENTORY",
    [QUEST_PLAYER] = "PLAYER",
    [QUEST_MERCHANT] = "MERCHANT",
    [QUEST_DUNGEON] = "DUNGEON",
    [QUEST_ARMOR] = "ARMOR",
    [QUEST_ROOM] = "ROOM",
    [QUEST_BOOK] = "BOOK",
    [QUEST_SHIELD] = "SHIELD",
    [QUEST_TAVERN] = "TAVERN",
    [QUEST_NPC] = "NPC",
    [QUEST_CHAIR] = "CHAIR",
    [QUEST_TABLE] = "TABLE",
    [QUEST_LIBRARY] = "LIBRARY",
    [QUEST_GEM] = "GEM",
    [QUEST_CONNECTOR_PASSAGE] = "CONNECTOR_PASSAGE",
    [QUEST_CONNECTOR_STAIRS] = "CONNECTOR_STAIRS"
};

#endif
